services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.deploy
    env_file:
      - .env
    expose:
      - ${FRONTEND_PORT}
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    env_file: 
      - .env
    environment:
      NODE_ENV: development
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    

  db:
    image: postgres
    restart: always
    env_file: 
      - .env
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT}:${DB_PORT}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    profiles: [tools]
    restart: always
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # expose ONLY nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - api

volumes:
  db-data:
  pgadmin-data: