name: Deploy to EC2

on:
  push:
    branches: [ 18-implement-api-data-fetching-logic ]

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SSH key
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      run:
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem

    - name: Clone repository
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
        echo "Current directory: $(pwd)"
        echo "Listing home directory:"
        ls -la ~

        REPO_URL="https://github.com/FrankenBunny/marquee-rental-webapp"
        BRANCH="18-implement-api-data-fetching-logic"
        REPO_DIR="$HOME/marquee-rental-webapp"

        if [ -d "$REPO_DIR/.git" ]; then
          cd "$REPO_DIR"
          git fetch origin
          if git show-ref --verify --quiet refs/heads/"$BRANCH"; then
            git checkout "$BRANCH"
          else
            git checkout -b "$BRANCH" origin/"$BRANCH"
          fi
          git reset --hard origin/"$BRANCH"
        else
          git clone --branch "$BRANCH" --single-branch "$REPO_URL" "$REPO_DIR"
          cd "$REPO_DIR"
        fi
        '

    - name: Create .env file
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
        FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
        API_PORT: ${{ secrets.API_PORT }}
        DB_PORT: ${{ secrets.DB_PORT }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      run: |
        touch .env
        echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" > .env
        echo "FRONTEND_ORIGIN=${{ secrets.FRONTEND_ORIGIN }}" > .env
        echo "API_PORT=${{ secrets.API_PORT }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "VITE_API_URL"=${{ secrets.VITE_API_URL }} >>.env
        echo "FRONTEND_ORIGIN"=${{ secrets.FRONTEND_ORIGIN }} >>.env
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        
        scp -v -i github-ec2.pem -o StrictHostKeyChecking=no .env ${USER}@${HOST}:~/marquee-rental-webapp/.env

    - name: Cleanup compose
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} bash -s << 'EOF'
      
        cd marquee-rental-webapp || exit 1

        echo "🧹 Cleaning up all previous Docker containers, images, volumes, and cache"
        sudo docker rm -f $(sudo docker ps -aq) || true
        sudo docker rmi -f $(sudo docker images -q) || true
        sudo docker volume rm $(sudo docker volume ls -q) || true
        sudo docker builder prune -af || true
        sudo docker network prune -f || true
    
    - name: Build containers
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} bash -s << EOF
        
        cd marquee-rental-webapp

        echo "📦 Building fresh containers"
        sudo docker compose -f compose.deploy.yaml down --volumes --remove-orphans
        sudo docker compose -f compose.deploy.yaml up -d --build

        echo "🧼 Removing .env (if any)"
        rm -f .env

        echo "✅ Deployment complete"
        EOF

    - name: Remove temporary files
      run: |
        rm -f .env
        rm -f github-ec2.pem